name: ci

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    code-style:
        runs-on: windows-10
        steps:
            -   name: Checkout
                uses: actions/checkout@v4
                with:
                    submodules: recursive
            -   uses: ilammy/msvc-dev-cmd@v1
            -   name: Check code style
                shell: cmd
                run: |
                    cmake -GNinja -B build .
                    cmake --build build -- check-format

    windows:
        needs: code-style
        runs-on: windows-10
        strategy:
            matrix:
                arch:
                    - amd64
                    - x86
                    - amd64_arm64
        steps:
            -   name: Checkout
                uses: actions/checkout@v4
                with:
                    submodules: recursive
            -   uses: ilammy/msvc-dev-cmd@v1
                with:
                    arch: ${{ matrix.arch }}
            -   name: Build
                shell: cmd
                run: |
                    cmake -GNinja -B build .
                    cmake --build build -- all
            -   name: Test
                if: ${{ matrix.arch != 'amd64_arm64' }}
                shell: cmd
                run: |
                    cmake --build build -- check

    macos:
        needs: code-style
        runs-on: macos-12-amd64
        strategy:
            matrix:
                arch:
                    - x86_64
                    - arm64
        steps:
            -   name: Checkout
                uses: actions/checkout@v4
                with:
                    submodules: recursive
            -   name: Build
                run: |
                    cmake -DCMAKE_OSX_ARCHITECTURES=${{matrix.arch}} -GNinja -B build .
                    cmake --build build -- all
            -   name: Test
                if: ${{ matrix.arch != 'arm64' }}
                run: |
                    cmake --build build -- check

    linux:
        needs: code-style
        runs-on: ubuntu-2204
        steps:
            -   name: Checkout
                uses: actions/checkout@v4
                with:
                    submodules: recursive
            -   name: Build
                run: |
                    cmake -GNinja -B build .
                    cmake --build build -- all
            -   name: Test
                run: |
                    cmake --build build -- check
